
const Maneno = [
"adamu","adabu","adimu","afiki","alika","ambao","amana","amuru","hitma","barua","bisha","bunda","hatua","hamna","hafla","elimu","hatia","huria","fikra","azizi","fursa","fuska","funza","kataa","pakaa","ngano","ngazi","uhuni","mhuni","mkora","ukora","kauli","kauka","hiari","asili",
"ghala","bikra","tamko","logwa","njuga","njugu","nyuki","chuki","wembe","nembo","tembo","jimbo","tumbo","wimbo","nywea","nyusi","kingo","kamua","mpira", "panda","pango","punda","mimea","stadi","mtepe","mwake","tenga","mfano","kodoa", "podoa","jazba","nanga","baina","rarua","kanga",
"nyuso","nyuzi","urefu","ufupi","uzuri","kabla","labda","ladha","kasha","washa","kwetu","mwana","kwata","kinda","winda","basha","kutwa","msongo","rukwa","sanda","jenga","ngeli","ngebe","ngiri","jungu","ukoko","utepe","menya","minya","nyaya","jeuri","angua","vumbi","baini","lango",
"kurwa", "kudra", "murwa", "tumwa", "fumwa", "shari", "shavu", "shari", "ficha", "fugwa", "futwa", "pinda", "pinga", "pimbi", "gimbi", "mbuzi", "mjusi", "msitu", "mbinu", "mbezi", "tenzi", "teuzi", "fungo","fungu","mfumo","mfuma","mfiwa","kamwe","chuna","sugua","mnene","sembe",
"mwezi","mwiba","mwitu","mwizi","mungu","tupia","rusha","vusha","shuka","tukio","tulio","kituo","vituo","gulio","kilio","vilio","dunia","zulia","mafua","fuata","gunia","gundi","njama","njema","vyama","nyuso","nyuma","mgema","mgomo","mgeni","kamba","kambo","tanga","tairi","chana",
"chuma", "vyuma", "dunga", "dunda", "funga", "fundo", "tunga", "tungo", "tunza", "uongo", "gonga", "gongo", "ponda", "bonge", "bunge", "hatua", "gutua", "ulezi", "ulimi", "ndimi", "ndizi", "gwiji", "gushi", "tunda", "tundu", "milio", "titia", "mbali", "mbili", "mgawo", "mbawa", "ezeka", "mboni", "ikulu","posho",
"totoa","tatua","choma","chuja","chuma","chupa","vyuma","mlima","dimba","swala","simba","tibua","tabia","taifa","wengi","weusi","weupe","cheua","tausi","doria","bundi","banda","banzi","kanda","kando","gaidi","mdomo","mdogo","mkosi","tumia","mkeka","mkazo","mkazi","enezi","eneza","mbata", "ambua",
"kubwa","ndafu","ndogo","ndefu","ndege","vifaa","kifaa","kifuu","rufaa","idhaa","mpito","utupu","upupu","uzuri","uhuru","chafu","kwato","mlima","wingu","wingi","donoa","bofya","mbega","mbogo","mboga","fulia","mrija","kwaza","kiazi","viazi","josho","duara","lugha","balaa","asali","ikiwa","iwapo",
"fumua","tanua","tania","utani","ubani","gingi","ujima","unene","umeme","tembo","yumba","tunda","fumbo","fumba","gumba","pingu","rungu","ndugu","bwege","togwa","songa","rukia","rundo","ruksa","ramli","ombea","pokea","mkoba","mkebe","kiuno","ganda","mbege","mbuga","usiku","tusua", "ndama",
"ongea","insha","ardhi","purua","pumua","tumba","rumba","gumba","rudia","papai","parua","haswa","maini","hisia","hulka","bamia","bania","anika","pamba","gamba","tango","tangu","dimba","yumba","mtutu","kulia","shoka","choka","mkato","mkate","funua","chota","chozi","tegua","panua","mamba",
"ufuta","ukuta","mkojo","uliza","halua","ajabu","hongo","binti","fedha","bezwa","hujma","vyuma","chuma","chura","vyura","kenge","pembe","tembe","jembe","kiatu","viatu","umati","udaku","njano","karai","nguli", "mpake","mjane","mbuni","jioni","jando","pambo","jamii","jamaa","upole",
"mayai","inuka","inama","ingia","bomoa","mzizi","mwizi","mwewe","mzuka","mpaka","ndani","panga","janga","kofia","chepe","lindo","linda","ringa","kipya","jipya","lipya","vipya","jambo","jumba","jumla","mambo","kwako","kwake","laana","laani","fyata","eleza","toboa","kagua","limao",
"jogoo", "nguzo", "komeo", "epuka", "mtoto", "mtoki", "mtoro", "mpera", "mnazi", "mvuvi", "mvivu", "janga", "tango", "tamba", "uliza", "umiza", "upepo", "kiapo", "viapo", "ulipo", "ufupi", "rithi", "zimua", "zubaa", "fukua", "uvumi","mauti","sikio","pitia","palia","uhaba","julia",
"pumua","nunua","mende","tende","iliki","faulu","gairi","wosia","ungua","dukua","dokoa","samli","titia","tulia","kwaya","vimba","mimba","pakua","pekua","penda","penzi","pendo","pepea","mdomo","wanga","wangu","taifa","kinga","kimya","jicho","macho","bwawa","gwaya","utata","lipia",
"ghuba","shaka","shuku","fagia","fagio","komeo","namba","njano","anika","wenge","ibuka","itika","ungwa","utoro","nondo","nyufa","mfupa","vulia","wanja","ujira","ujuzi","kundi","ngoja","bomba","hivyo","sivyo","hamia","bidii","faida","faidi","fidia","azima","vizia","tuama"]

export default Maneno